# Generated by Django 6.1 on 2026-09-03 12:57

import django.db.models.deletion
import meetings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_date', models.DateField()),
                ('minutes', models.TextField(help_text='Compte-rendu de la réunion (texte libre ou collé)')),
                ('attendance_sheet', models.FileField(help_text='Fiche de présence scannée (PDF) avec signatures manuscrites', upload_to=meetings.models.attendance_sheet_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
    ]
