# Generated by Django 6.1 on 2026-09-03 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('team', models.CharField(help_text='Quart ayant rédigé le rapport (Car1-4/MRSC)', max_length=20)),
                ('summary', models.TextField(help_text='Synthèse des événements des dernières 24h')),
                ('alerts_count', models.PositiveIntegerField(default=0)),
                ('rescues_count', models.PositiveIntegerField(default=0)),
                ('coordinations_count', models.PositiveIntegerField(default=0)),
                ('calls_received_count', models.PositiveIntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='centers.center')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports_created', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('center', 'report_date', 'team')},
            },
        ),
    ]
