# Generated by Django 6.1 on 2026-08-31 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('is_victim', models.BooleanField(default=False)),
                ('status_note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('call_time', models.DateTimeField(help_text="Heure exacte de l'appel/signalement")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('position_text', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('QUALIFIED', 'Qualifiée'), ('TRANSMITTED', 'Transmise au partenaire'), ('CLOSED', 'Clôturée')], default='NEW', max_length=20)),
                ('operator_signature', models.CharField(help_text="Nom de famille de l'opérateur (saisie manuelle obligatoire)", max_length=100)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='references.incidentcategory')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='centers.center')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='references.alertsource')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-call_time'],
            },
        ),
    ]
