# Generated by Django 6.1 on 2026-08-31 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vessels.vessel'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertperson',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_people', to='alerts.alert'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['call_time'], name='alerts_aler_call_ti_c8c318_idx'),
        ),
    ]
