# Generated by Django 6.1 on 2026-08-31 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0003_initial'),
        ('references', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('status_note', models.TextField(blank=True)),
                ('handled_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='alerts.alert')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='references.personrole')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='references.personstatus')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
