# Generated by Django 6.1 on 2026-08-31 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0003_initial'),
        ('centers', '0001_initial'),
        ('partners', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('registration', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ENGAGED', 'Engagé'), ('UNAVAILABLE', 'Indisponible / maintenance')], default='AVAILABLE', max_length=20)),
                ('home_base', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='means', to='centers.center')),
                ('means_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='means', to='references.meanstype')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='means', to='partners.partner')),
            ],
            options={
                'verbose_name_plural': 'Means',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeansEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engaged_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('mission_role', models.CharField(blank=True, max_length=200)),
                ('report', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='alerts.alert')),
                ('engaged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('means', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='sar.means')),
            ],
            options={
                'ordering': ['-engaged_at'],
            },
        ),
    ]
