# Generated by Django 6.1 on 2026-08-31 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('flag', models.CharField(blank=True, max_length=100, verbose_name='Pavillon')),
                ('mmsi', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='MMSI')),
                ('imo', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Numéro IMO')),
                ('call_sign', models.CharField(blank=True, max_length=30)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('crew_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='references.vesseltype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
