# Generated by Django 6.1 on 2026-08-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('center_type', models.CharField(choices=[('MRCC', 'MRCC'), ('MRSC', 'MRSC')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
